hzuapps/android-labs-2017

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903226/Net1414080903226Activity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903226.xml
=> #1 #10  第一次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/Net1414080903218Activity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903218.xml
=> #1 #24 第一次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903230/Net1414080903230Activity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903230.xml
=> #1 #15 第一次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903217/PhotoNet1414080903217.java, AndroidLabs/app/src/main/res/layout/activity_photo_net1414080903217.xml
=> #3 #106 第三次作业

AndroidLabs/app/src/main/res/layout/activity_net1414080903117.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_menu.xml
曾老师，您好。我在实验2时已经完成了实验4的内容，所以这次提交的实验4相对于实验2是基本没什么改变的。麻烦您查阅一下，谢谢！
=> #4 #128 第四次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903212/Net1414080903212Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903212/Net1414080903212SecondFragment.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903212.xml, AndroidLabs/app/src/main/res/layout/first_fragment1414080903212.xml, AndroidLabs/app/src/main/res/layout/second_fragment1414080903212.xml
=> #4 #13 第四次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903112/net1414080903112Activity.java, AndroidLabs/app/src/main/res/layout/activity_result1414080903112.xml, AndroidLabs/app/src/main/res/layout/activity_select1414080903112.xml
=> #4 #16 第四次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Net1414080903110_SubmitActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Net1414080903110_WorkListActivity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903110_login.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903110_submit.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903110_worklist.xml, AndroidLabs/app/src/main/res/layout/net1414080903110_work_item.xml
之前在实验2的时候已经完成了app的页面布局以及一些控件的控制；
这次就做了点小改动，麻烦老师查阅！以下是作业列表的截图！
=> #4 #36 第四次作业

AndroidLabs/app/src/main/res/layout/activity_main_net1414080903232.xml
=> #4 #48 第4次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Note.java, AndroidLabs/app/src/main/res/drawable/mycolor_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/note_net1414080903213.xml
=> #4 #20 第四次实验

AndroidLabs/app/src/main/res/layout/activity_main_net1409081602222.xml, AndroidLabs/app/src/main/res/layout/activity_menu_net1409081602222.xml
曾老师，您好。我在实验2时已经完成了实验4的内容，所以这次提交的实验4相对于实验2是基本没什么改变的。麻烦您查阅一下，谢谢！
=> #4 #39 第四次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903201/Net1414080903201Activity01.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903201/Net1414080903201Activity02.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903201/Net1414080903201User.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903201Activity01.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903201Activity02.xml
=> #2 #32 第二次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/AutoPlayer.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/ChessView.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/Net1414080903218Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/Net1414080903218BoardActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/NetPlayer.java, AndroidLabs/app/src/main/res/drawable/button_net1414080903218.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903218.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903218_board.xml
=> #4 #24 第四次实验

AndroidLabs/app/src/main/res/layout/activity_net1414080903209.xml
=> #3 #31 第三次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903230/Net1414080903230_DiaryFragment.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903230/Net1414080903230_WriteDiaryActivity.java
=> #5 #15 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903222/FirstFragment1414080903222.java
=> #5 #27 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117FeeActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117MainActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117MenuActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117MySQLiteOpenHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117RecordActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117RecordBean.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117SubmitActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903117/Net1414080903117TimeUtil.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_fee.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_main.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_menu.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_record.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903117_submit.xml, AndroidLabs/app/src/main/res/layout/item_net1414080903117_recoed.xml
曾老师，您好，这次实验我做了数据库的内容以及把app的界面、功能完善了。
=> #5 #128 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903127/Net1414080903127GameActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903127/Net1414080903127RankActivity.java
在第4次实验交的GameActivity的SaveGrade方法和RankActivity的GetGrade方法里面使用了Preferences方法存储数据。
=> #5 #28 第5次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Net1414080903110_LoginActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Net1414080903110_SubmitActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Net1414080903110_WorkListActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/WorkAdapter.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/WorkDatabaseHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903110/Work_Info.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903110_submit.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903110_worklist.xml
这次实验除了做了数据库存储的，还修改了之前一些不合理的地方，
之前的作业是写死的，现在可以自主添加，删除，查看；麻烦老师查看！
=> #5 #36 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/AutoPlayer.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903218/Board.java
=> #5 #24 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/CostSQLiteOpenHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Income.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Incomedao.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Net1414080903234AddIncomeActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Net1414080903234AddOutlayActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Net1414080903234_I.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Net1414080903234_M.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Net1414080903234_O.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Outlay.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903234/Outlaydao.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903234.xml, AndroidLabs/app/src/main/res/layout/fragment_net1414080903234__i.xml, AndroidLabs/app/src/main/res/layout/fragment_net1414080903234__o.xml, AndroidLabs/app/src/main/res/layout/inlist_net1414080903234.xml, AndroidLabs/app/src/main/res/layout/outlist_net1414080903234.xml
=> #5 #19 实验5

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_AddSchedule.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Data.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Note.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Schedule.java, AndroidLabs/app/src/main/res/layout/addschedule_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/list_sch_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/note_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/schedule_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/theme_net1414080903213.xml
使用了SQLite进行存储，用listview将日程内容以列表形式显示，可以删除、修改已有的日程内容。
=> #5 #20 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903232/AccountDao.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903232/ItemInfo.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903232/MainActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903232/MyHelper.java
由于操作数据库的需要（删查改）在ItemInfo类中添加了属性 id；
新增加MyHelper类，用于创建数据库；
新增加AccountDao类，用于操作数据库；
由于我的用户为店主，店主只被允许查看操作数据库的内容（订单）；
并在查看订单的同时，也就是在点击按钮后，会将数据保存到数据库并通过Intent对象将数据传到另一个界面用于显示订单详情。
=> #5 #48 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903106/MyApplication.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903106/Net1414080903106City.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903106/Net1414080903106CityDB.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903106/Net1414080903106SelectCity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903106_select_city.xml
本次实验通过查找数据库文件city.db的city表中的city获取其number，并传递到MainActivity中。
=> #5 #33 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/DancibenActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/FirstActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/MyDatabaseHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/StudyActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/Word.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/ZhujiemianActivity.java, AndroidLabs/app/src/main/res/layout/danciben_net1414080903219.xml, AndroidLabs/app/src/main/res/layout/first_net1414080903219.xml, AndroidLabs/app/src/main/res/layout/listitem_net1414080903219.xml, AndroidLabs/app/src/main/res/layout/zhujiemian_net1414080903219.xml
=> #5 #153 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_NewAccount.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_OrderRecord.java
使用内部存储
将账目记录后以进度条的形式展现个消费项所占的百分比
=> #5 #30 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/ChatActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/CreateGroupActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/GroupListActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/JoinGroupActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/LoginActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/RegisterActivity.java, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_chat.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_create_group.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_group_list.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_join_group.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_login.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_activity_register.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_group_item.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_item_join_group.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_item_message.xml, AndroidLabs/app/src/main/res/layout/net1414080903120_item_message_self.xml
加的内容比较多，以及上次请假了忘了交。合并了这个再把第五次交了
=> #4 #12 第四次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903229/CreateSchedule.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903229/PlanInfo.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903229/PlansService.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903229/UpdateSchedule.java
这次合并的文件实现的功能
1.文件的存储，以xml文件方式存储和调取数据内容
2.新建计划提交后存储计划内容，修改计划调取计划内容显示，修改提交后再次存储
=> #1 #43 第五次试验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903120/ui/LoginActivity.java
不小心和第四次一起交了。用到了sharePreference算文件吗？
=> #5 #12 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903224/N1414080903224Address.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903224/N1414080903224Dao.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903224/N1414080903224MyHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903224/Net1414080903224Internet.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903224_internet.xml
=> #5 #63 第五次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_AccountDetail.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_NewAccount.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_OldAccount.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_OrderRecord.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/Net1414080903240_chose.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/detailvalues.xml, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903240/order.java
=> #6 #30 第六次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903217/MyHelper.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903217/Mypicture.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903217/PictureDao.java
=> #5 #106 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/DancibenActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/JsonActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/data.xml, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903219/getdata.json, AndroidLabs/app/src/main/res/layout/danciben_net1414080903219.xml, AndroidLabs/app/src/main/res/layout/json_net1414080903219.xml
使用HttpURLConnection访问网络，获取json文件并解析。json文件在second commit那里可查看。
=> #6 #153 第六次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903226/Net1414080903226AudioReceiver.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903226/Net1414080903226AudioSender.java
这次实验是网络编程，我根据我的项目的要求，做了个实时语音对讲的功能，完整代码可到我的项目仓库查看：https://github.com/wetstreet/Theircraft
=> #6 #10 第六次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903116/Net1414080903116Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903116/Net1414080903116AnalysisJson.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903116/Net141408093116SoftInfo.json, AndroidLabs/app/src/main/res/layout/activity_net1414080903116.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903116_analysis_json.xml
点击“软件信息”按钮，从github上获取json数据并解析出来。
=> #6 #21 第六次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903213/Net1414080903213_GetXml.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903213.xml, AndroidLabs/app/src/main/res/layout/get_xml_net1414080903213.xml, test2_1414080903213.xml, testfile_1414080903213.xml
使用Jsoup解析器，根据url地址解析xml文件，在Android Studio使用时需要加入其jar包
xml文件地址：https://github.com/liuzezhao/android-labs-2017/blob/master/testfile_1414080903213.xml
=> #6 #20 第六次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903112/Net1414080903112Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903112/result1414080903112.java
=> #5 #16 第五次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903109/Net1414080903109MainActivity.java, AndroidLabs/app/src/main/res/layout/activity_net1414080903109_main.xml
老师你好，我的作业名原本是“考生报考指南”，但是想了很多之后觉得没办法实现。首先填报志愿是需要非常认真对待的事情，每年高校的投档线和录取排名都会有变动，无法预测。万一给用户提供了不合适的选择，造成考生填报了错误的学校，可能会承担很大的责任。之前电脑故障了很长一段时间，做不了实验，这阵子已经修理好，把题目改成了现在的“节假日提醒”，到现在才交实验，增加老师额外的工作量，我表示非常抱歉。
=> #1 #178 第一次作业

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903232/MainActivity.java, AndroidLabs/app/src/main/res/layout/activity_lujin_net1414080903232.xml, AndroidLabs/app/src/main/res/layout/activity_main_net1414080903232.xml, activity_lujin_net1414080903232.xml
在这个实验中，使用了网络编程，实现HTTP请求到响应的整个过程。
解析URL所包含的内容。
图片中，红色方框部分为点击”解析xml“按钮后获得的数据。
=> #6 #48 第6次实验

AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903104/Net1414080903104Activity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903104/Net1414080903104obtainjsonActivity.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903104/Sentence.java, AndroidLabs/app/src/main/java/edu/hzuapps/androidlabs/homeworks/net1414080903104/jsoninfornation.json, AndroidLabs/app/src/main/res/layout/obtainjson_net1414080903104.xml
本次实验是参考书本HttpURLConnection来访问的网络，并利用org.json包解析json数据。操作结果如下：
提问：老师，不知道为什么，我在用url获取json数据的时候，获取到的字符串格式是null["xxx":"xxx"]，就是会有个null前面，可是在原先的json文件内的'['前，我并没有输入任何字符，甚至使用其他网站的公开api获取到的json数据都是这样。我使用的解决方法是将字符串内去掉null，但搞不明白为什么会出现null，而且卡在这里很久了。
=> #6 #22 第六次实验 

AndroidLabs/app/src/main/res/layout/activity_net1414080903201news_graduetest5.xml, AndroidLabs/app/src/main/res/layout/activity_net1414080903201news_vediotest5.xml
=> #5 #32 第五次作业
